name: Docker Image CI for GHCR

on:
  [workflow_dispatch]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build and push the image
      run: |
        docker login --username javeedambu --password ${{secrets.GITHUB_TOKEN}} ghcr.io
        docker build . --tag ghcr.io/javeedambu/hello-world-dhcr:latest
        docker push  ghcr.io/javeedambu/hello-world-ghcr:latest
